# Configuration Mosquitto pour le projet IoT
# Éclairage public intelligent
# Auteur : babourwel2001-cpu

listener 1883 0.0.0.0
allow_anonymous true
log_dest stdout
log_type all
connection_messages true